import ast, base64, pathlib

TARGET = pathlib.Path("modules/net/scan.py")
MAIN = base64.b64decode("ZGVmIG1haW4oYXJndjogbGlzdFtzdHJdKSAtPiBpbnQ6CiAgICAiIiJDTEkgZW50cnkgcG9pbnQ6IHJ1biB0aGlzIG1vZHVsZSdzIHNjYW4gZnVuY3Rpb24gb24gYSBob3N0LiIiIgogICAgaW1wb3J0IGFyZ3BhcnNlCiAgICBpbXBvcnQgaW5zcGVjdAogICAgaW1wb3J0IGpzb24KICAgIGltcG9ydCBzeXMKCiAgICBtb2R1bGUgPSBzeXMubW9kdWxlc1tfX25hbWVfX10KICAgIGZ1bmNzID0gewogICAgICAgIG5hbWU6IG9iagogICAgICAgIGZvciBuYW1lLCBvYmogaW4gdmFycyhtb2R1bGUpLml0ZW1zKCkKICAgICAgICBpZiBpbnNwZWN0LmlzZnVuY3Rpb24ob2JqKQogICAgICAgIGFuZCBub3QgbmFtZS5zdGFydHN3aXRoKCJfIikKICAgICAgICBhbmQgbmFtZSAhPSAibWFpbiIKICAgICAgICBhbmQgZ2V0YXR0cihvYmosICJfX21vZHVsZV9fIiwgTm9uZSkgPT0gbW9kdWxlLl9fbmFtZV9fCiAgICB9CiAgICBpZiBsZW4oZnVuY3MpICE9IDE6CiAgICAgICAgcHJpbnQoCiAgICAgICAgICAgICJuZXQtc2NhbjogZXhwZWN0ZWQgZXhhY3RseSBvbmUgcHVibGljIGZ1bmN0aW9uIHRvIHdpcmUsICIKICAgICAgICAgICAgZiJmb3VuZCB7c29ydGVkKGZ1bmNzKX0uIFRlbGwgdGhlIG1haW50YWluZXIgd2hpY2ggdG8gdXNlLiIsCiAgICAgICAgICAgIGZpbGU9c3lzLnN0ZGVyciwKICAgICAgICApCiAgICAgICAgcmV0dXJuIDIKICAgIChmbmFtZSwgZnVuYyksID0gZnVuY3MuaXRlbXMoKQogICAgc2lnID0gaW5zcGVjdC5zaWduYXR1cmUoZnVuYykKCiAgICBwYXJzZXIgPSBhcmdwYXJzZS5Bcmd1bWVudFBhcnNlcigKICAgICAgICBwcm9nPSJuZXQtc2NhbiIsCiAgICAgICAgZGVzY3JpcHRpb249ZiJSdW4ge2ZuYW1lfSgpIGZyb20gdGhpcyBtb2R1bGUuIikKICAgIHBhcnNlci5hZGRfYXJndW1lbnQoImhvc3QiLCBoZWxwPSJUYXJnZXQgaG9zdCBvciBJUCBhZGRyZXNzLiIpCiAgICBwYXJzZXIuYWRkX2FyZ3VtZW50KAogICAgICAgICItcCIsICItLXBvcnQiLCB0eXBlPWludCwgZGVmYXVsdD1Ob25lLAogICAgICAgIGhlbHA9Ik9wdGlvbmFsIHRhcmdldCBwb3J0ICh1c2VkIG9ubHkgaWYgdGhlIGZ1bmN0aW9uIGFjY2VwdHMgaXQpLiIpCiAgICBhcmdzID0gcGFyc2VyLnBhcnNlX2FyZ3MoYXJndikKCiAgICBrd2FyZ3MgPSB7fQogICAgaWYgInBvcnQiIGluIHNpZy5wYXJhbWV0ZXJzIGFuZCBhcmdzLnBvcnQgaXMgbm90IE5vbmU6CiAgICAgICAga3dhcmdzWyJwb3J0Il0gPSBhcmdzLnBvcnQKCiAgICByZXN1bHQgPSBmdW5jKGFyZ3MuaG9zdCwgKiprd2FyZ3MpCiAgICBpZiBpc2luc3RhbmNlKHJlc3VsdCwgc3RyKToKICAgICAgICBwcmludChyZXN1bHQpCiAgICBlbHNlOgogICAgICAgIHByaW50KGpzb24uZHVtcHMocmVzdWx0LCBpbmRlbnQ9MiwgZGVmYXVsdD1zdHIpKQogICAgcmV0dXJuIDAK").decode()

src = TARGET.read_text(encoding="utf-8")
lines = src.splitlines()
cut = next((i for i, ln in enumerate(lines)
            if ln.startswith("def main(")), None)
if cut is not None:
    while cut > 0 and lines[cut - 1].strip() == "":
        cut -= 1
    lines = lines[:cut]
clean = "\n".join(lines).rstrip("\n")
new = clean + "\n\n\n" + MAIN
ast.parse(new)
TARGET.write_text(new, encoding="utf-8")
print("scan.py: main() replaced with name-agnostic version")

